version: '3'

services:
  todofront:    #nome dos services
    build: ./todo-app/front-end
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=localhost
    ports:
      - 3000:3000

  todoback:
    build: ./todo-app/back-end
    image: todobackend
    ports:
      - 3001:3001

  todotests:
    build: ./todo-app/tests
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  