version: '3'

services:
  todofront:    #nome dos services
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000

  todoback:
    image: todobackend
    ports:
      - 3001:3001

  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  